simjason.github.io
│
├ Home.py
├ requirements.txt
├ pages
│   ├ AboutMe.py
│   ├ Projects.py
│   ├ Experiences.py
│   └ Dashboard.py
│
└ .streamlit
    └ config.toml

    [theme]
base="light"

primaryColor="#4A90E2"

backgroundColor="#FFFFFF"

secondaryBackgroundColor="#F7F9FC"

textColor="#1F2937"

font="sans serif"
